apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer-secret
data:
  amqp_url: YW1xcDovL2RlZmF1bHRfdXNlcl9oVEdJNmZKeXN5STljN1JUaWREOkZNUmhveXFQYlo2MUpGcXVvOWlOMWRpRjV4OEduMi1YQDEwLjQzLjkzLjk1OjU2NzI=
---
apiVersion: v1
kind: Secret
metadata:
  name: rgw-s3-credential
data:
  aws_access_key: Mnc4QWJDUjhLSGxEaFFDRHczVVFHSEx6a3NNREd0N1NIb21BTTJFWg==
  aws_key_id: S0xZQlI4QjVIVUo0WUNUMU9QOE0=
  aws_endpoint_url: aHR0cDovLzEwLjQzLjEzNC44Mg==      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-consumer
  namespace: default
  labels:
    app: rabbitmq-consumer
spec:
  selector:
    matchLabels:
      app: rabbitmq-consumer
  template:
    metadata:
      labels:
        app: rabbitmq-consumer
    spec:
      containers:
        - name: rabbitmq-consumer
          image: quay.io/rootfs/kubecon21-demo:latest
          imagePullPolicy: IfNotPresent
          args:
          - func.py
          command:
          - python3
          env:
          - name: AMQP_URL
            valueFrom: 
              secretKeyRef:
                name: rabbitmq-consumer-secret
                key: amqp_url
          - name: AMQP_EXCHANGE
            value: ex1
          - name: AMQP_ROUTING_KEY
            value: demo
          - name: AMQP_QUEUE_NAME
            value: bucket-notification-queue
          - name: AWS_ENDPOINT_URL
            valueFrom: 
              secretKeyRef:
                name: rgw-s3-credential
                key: aws_endpoint_url
          - name: AWS_ACCESS_KEY_ID
            valueFrom: 
              secretKeyRef:
                name: rgw-s3-credential
                key: aws_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom: 
              secretKeyRef:
                name: rgw-s3-credential
                key: aws_access_key
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: rabbitmq-consumer  
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://default_user_hTGI6fJysyI9c7RTidD:FMRhoyqPbZ61JFquo9iN1diF5x8Gn2-X@10.43.93.95:5672/
        queueName: "bucket-notification-queue"
        queueLength: "5"
