apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer-secret
data:
  amqp_url: YW1xcDovL2RlZmF1bHRfdXNlcl9sX0JFenVwUVpCQWd5bThBMnQ5OnhmTkhnOWtzQkgxTUVhSFEtbHh3eE1GNjVNSkxzcDlVQDEwLjQzLjk2LjI0Nzo1Njcy
---
apiVersion: v1
kind: Secret
metadata:
  name: rgw-s3-credential
data:
  aws_access_key: QUFjV2xoMmN4ZTdNV25UMHhreXJyVFZ2QXc4TmEycXhteExROXZTZg==
  aws_key_id: NjY4MDRBQk1HT1dFS0hDOTBYVDc=
  aws_endpoint_url: aHR0cDovLzEwLjQzLjI1NC4yMDc=
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer
  namespace: default
spec:
  scaleTargetRef:
    deploymentName: rabbitmq-consumer
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://default_user_l_BEzupQZBAgym8A2t9:xfNHg9ksBH1MEaHQ-lxwxMF65MJLsp9U@10.43.96.247:5672
        queueName: "bucket-notification-queue"
        queueLength: "5"
      authenticationRef:
        name: rabbitmq-consumer-trigger
---
apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-consumer-trigger
  namespace: default
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-consumer-secret
    key: amqp_url
